// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"database/sql"
)

type Entity struct {
	ID                 int64          `json:"id"`
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	Description        sql.NullString `json:"description"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
}

type EntityType struct {
	ID          int64          `json:"id"`
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
}

type MediaAsset struct {
	ID                    int64          `json:"id"`
	Type                  string         `json:"type"`
	R2Key                 sql.NullString `json:"r2_key"`
	YoutubeID             sql.NullString `json:"youtube_id"`
	SourcePromptVersionID sql.NullInt64  `json:"source_prompt_version_id"`
	CreatedAt             sql.NullTime   `json:"created_at"`
}

type PromptType struct {
	ID           int64          `json:"id"`
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	TemplateText string         `json:"template_text"`
}

type PromptVersion struct {
	ID                  int64          `json:"id"`
	EntityID            int64          `json:"entity_id"`
	TypeID              int64          `json:"type_id"`
	VersionNumber       int64          `json:"version_number"`
	PromptText          string         `json:"prompt_text"`
	TechnicalParamsJson sql.NullString `json:"technical_params_json"`
	CreatedAt           sql.NullTime   `json:"created_at"`
}

type Story struct {
	ID            int64          `json:"id"`
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Published     sql.NullBool   `json:"published"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type StoryItem struct {
	ID           int64 `json:"id"`
	StoryID      int64 `json:"story_id"`
	MediaAssetID int64 `json:"media_asset_id"`
	SortOrder    int64 `json:"sort_order"`
}

type User struct {
	ID        int64          `json:"id"`
	Email     string         `json:"email"`
	GoogleID  string         `json:"google_id"`
	Role      sql.NullString `json:"role"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
