// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	AddStoryItem(ctx context.Context, arg AddStoryItemParams) (StoryItem, error)
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error)
	CreatePromptType(ctx context.Context, arg CreatePromptTypeParams) (PromptType, error)
	CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error)
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	DeleteEntity(ctx context.Context, id int64) error
	DeletePromptType(ctx context.Context, id int64) error
	DeleteStoryItem(ctx context.Context, id int64) error
	GetEntityByID(ctx context.Context, id int64) (Entity, error)
	GetEntityBySlug(ctx context.Context, slug string) (Entity, error)
	GetLatestPromptVersion(ctx context.Context, arg GetLatestPromptVersionParams) (PromptVersion, error)
	GetMediaAsset(ctx context.Context, id int64) (MediaAsset, error)
	GetPromptTypeByID(ctx context.Context, id int64) (PromptType, error)
	GetPromptTypeBySlug(ctx context.Context, slug string) (PromptType, error)
	GetPromptVersionByID(ctx context.Context, id int64) (PromptVersion, error)
	GetStoryByID(ctx context.Context, id int64) (Story, error)
	GetStoryBySlug(ctx context.Context, slug string) (Story, error)
	GetStoryItems(ctx context.Context, storyID int64) ([]StoryItem, error)
	GetStoryWithItems(ctx context.Context, id int64) (GetStoryWithItemsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	ListAllMediaAssets(ctx context.Context) ([]MediaAsset, error)
	ListAllPromptVersions(ctx context.Context) ([]PromptVersion, error)
	ListAllStories(ctx context.Context) ([]Story, error)
	ListEntities(ctx context.Context) ([]Entity, error)
	ListEntitiesByType(ctx context.Context, type_ string) ([]Entity, error)
	ListMediaByStory(ctx context.Context, storyID int64) ([]MediaAsset, error)
	ListPromptTypes(ctx context.Context) ([]PromptType, error)
	ListPromptVersionsForEntity(ctx context.Context, entityID int64) ([]PromptVersion, error)
	ListPromptVersionsForEntityAndType(ctx context.Context, arg ListPromptVersionsForEntityAndTypeParams) ([]PromptVersion, error)
	ListPublishedStories(ctx context.Context) ([]Story, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error)
	UpdatePromptType(ctx context.Context, arg UpdatePromptTypeParams) error
	UpdateStoryItemSortOrder(ctx context.Context, arg UpdateStoryItemSortOrderParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
