// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	AddStoryItem(ctx context.Context, arg AddStoryItemParams) (StoryItem, error)
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateEntityType(ctx context.Context, arg CreateEntityTypeParams) (EntityType, error)
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error)
	CreatePromptType(ctx context.Context, arg CreatePromptTypeParams) (PromptType, error)
	CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error)
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	DeleteEntity(ctx context.Context, id int64) error
	DeleteEntityType(ctx context.Context, id int64) error
	DeletePromptType(ctx context.Context, id int64) error
	DeleteStory(ctx context.Context, id int64) error
	DeleteStoryItem(ctx context.Context, id int64) error
	GetEntityByID(ctx context.Context, id int64) (GetEntityByIDRow, error)
	GetEntityBySlug(ctx context.Context, slug string) (GetEntityBySlugRow, error)
	GetEntityTypeByID(ctx context.Context, id int64) (EntityType, error)
	GetEntityTypeBySlug(ctx context.Context, slug string) (EntityType, error)
	GetLatestPromptVersion(ctx context.Context, arg GetLatestPromptVersionParams) (PromptVersion, error)
	GetLatestPromptVersionForMatrix(ctx context.Context, arg GetLatestPromptVersionForMatrixParams) (GetLatestPromptVersionForMatrixRow, error)
	GetMediaAsset(ctx context.Context, id int64) (MediaAsset, error)
	GetPromptTypeByID(ctx context.Context, id int64) (PromptType, error)
	GetPromptTypeBySlug(ctx context.Context, slug string) (PromptType, error)
	GetPromptVersionByID(ctx context.Context, id int64) (PromptVersion, error)
	GetStoryByID(ctx context.Context, id int64) (Story, error)
	GetStoryBySlug(ctx context.Context, slug string) (Story, error)
	GetStoryItems(ctx context.Context, storyID int64) ([]StoryItem, error)
	GetStoryWithItems(ctx context.Context, id int64) (GetStoryWithItemsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	ListAllMediaAssets(ctx context.Context) ([]MediaAsset, error)
	ListAllPromptVersions(ctx context.Context) ([]PromptVersion, error)
	ListAllStories(ctx context.Context) ([]Story, error)
	ListEntities(ctx context.Context) ([]ListEntitiesRow, error)
	ListEntitiesByType(ctx context.Context, lower string) ([]ListEntitiesByTypeRow, error)
	ListEntityTypes(ctx context.Context) ([]EntityType, error)
	ListMediaByStory(ctx context.Context, storyID int64) ([]MediaAsset, error)
	ListPromptTypes(ctx context.Context) ([]PromptType, error)
	ListPromptVersionsForEntity(ctx context.Context, entityID int64) ([]PromptVersion, error)
	ListPromptVersionsForEntityAndType(ctx context.Context, arg ListPromptVersionsForEntityAndTypeParams) ([]PromptVersion, error)
	ListPublishedStories(ctx context.Context) ([]Story, error)
	ListRecentPromptVersions(ctx context.Context) ([]ListRecentPromptVersionsRow, error)
	ListUsers(ctx context.Context) ([]User, error)
	UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error)
	UpdateEntityType(ctx context.Context, arg UpdateEntityTypeParams) (EntityType, error)
	UpdatePromptType(ctx context.Context, arg UpdatePromptTypeParams) error
	UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error)
	UpdateStoryItemSortOrder(ctx context.Context, arg UpdateStoryItemSortOrderParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
