// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package repository

import (
	"context"
	"database/sql"
)

const addStoryItem = `-- name: AddStoryItem :one
INSERT INTO story_items (story_id, media_asset_id, sort_order)
VALUES (?, ?, ?)
RETURNING id, story_id, media_asset_id, sort_order
`

type AddStoryItemParams struct {
	StoryID      int64 `json:"story_id"`
	MediaAssetID int64 `json:"media_asset_id"`
	SortOrder    int64 `json:"sort_order"`
}

func (q *Queries) AddStoryItem(ctx context.Context, arg AddStoryItemParams) (StoryItem, error) {
	row := q.db.QueryRowContext(ctx, addStoryItem, arg.StoryID, arg.MediaAssetID, arg.SortOrder)
	var i StoryItem
	err := row.Scan(
		&i.ID,
		&i.StoryID,
		&i.MediaAssetID,
		&i.SortOrder,
	)
	return i, err
}

const createEntity = `-- name: CreateEntity :one
INSERT INTO entities (slug, name, type, entity_type_id, description, base_prompt, avatar_url, avatar_thumbnail_url)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
RETURNING id, slug, name, type, description, avatar_url, created_at, base_prompt, entity_type_id, avatar_thumbnail_url
`

type CreateEntityParams struct {
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	Description        sql.NullString `json:"description"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
}

func (q *Queries) CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, createEntity,
		arg.Slug,
		arg.Name,
		arg.Type,
		arg.EntityTypeID,
		arg.Description,
		arg.BasePrompt,
		arg.AvatarUrl,
		arg.AvatarThumbnailUrl,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.BasePrompt,
		&i.EntityTypeID,
		&i.AvatarThumbnailUrl,
	)
	return i, err
}

const createEntityType = `-- name: CreateEntityType :one
INSERT INTO entity_types (slug, name, description)
VALUES (?, ?, ?)
RETURNING id, slug, name, description, created_at
`

type CreateEntityTypeParams struct {
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
}

func (q *Queries) CreateEntityType(ctx context.Context, arg CreateEntityTypeParams) (EntityType, error) {
	row := q.db.QueryRowContext(ctx, createEntityType, arg.Slug, arg.Name, arg.Description)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const createMediaAsset = `-- name: CreateMediaAsset :one
INSERT INTO media_assets (type, r2_key, youtube_id, source_prompt_version_id)
VALUES (?, ?, ?, ?)
RETURNING id, type, r2_key, youtube_id, source_prompt_version_id, created_at
`

type CreateMediaAssetParams struct {
	Type                  string         `json:"type"`
	R2Key                 sql.NullString `json:"r2_key"`
	YoutubeID             sql.NullString `json:"youtube_id"`
	SourcePromptVersionID sql.NullInt64  `json:"source_prompt_version_id"`
}

func (q *Queries) CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, createMediaAsset,
		arg.Type,
		arg.R2Key,
		arg.YoutubeID,
		arg.SourcePromptVersionID,
	)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.R2Key,
		&i.YoutubeID,
		&i.SourcePromptVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const createPromptType = `-- name: CreatePromptType :one
INSERT INTO prompt_types (slug, description, template_text)
VALUES (?, ?, ?)
RETURNING id, slug, description, template_text
`

type CreatePromptTypeParams struct {
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	TemplateText string         `json:"template_text"`
}

func (q *Queries) CreatePromptType(ctx context.Context, arg CreatePromptTypeParams) (PromptType, error) {
	row := q.db.QueryRowContext(ctx, createPromptType, arg.Slug, arg.Description, arg.TemplateText)
	var i PromptType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Description,
		&i.TemplateText,
	)
	return i, err
}

const createPromptVersion = `-- name: CreatePromptVersion :one
INSERT INTO prompt_versions (entity_id, type_id, version_number, prompt_text, technical_params_json)
VALUES (?, ?, ?, ?, ?)
RETURNING id, entity_id, type_id, version_number, prompt_text, technical_params_json, created_at
`

type CreatePromptVersionParams struct {
	EntityID            int64          `json:"entity_id"`
	TypeID              int64          `json:"type_id"`
	VersionNumber       int64          `json:"version_number"`
	PromptText          string         `json:"prompt_text"`
	TechnicalParamsJson sql.NullString `json:"technical_params_json"`
}

func (q *Queries) CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, createPromptVersion,
		arg.EntityID,
		arg.TypeID,
		arg.VersionNumber,
		arg.PromptText,
		arg.TechnicalParamsJson,
	)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.TypeID,
		&i.VersionNumber,
		&i.PromptText,
		&i.TechnicalParamsJson,
		&i.CreatedAt,
	)
	return i, err
}

const createStory = `-- name: CreateStory :one
INSERT INTO stories (title, slug, cover_image_url, published)
VALUES (?, ?, ?, ?)
RETURNING id, title, slug, cover_image_url, published, created_at
`

type CreateStoryParams struct {
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Published     sql.NullBool   `json:"published"`
}

func (q *Queries) CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error) {
	row := q.db.QueryRowContext(ctx, createStory,
		arg.Title,
		arg.Slug,
		arg.CoverImageUrl,
		arg.Published,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.CoverImageUrl,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const deleteEntity = `-- name: DeleteEntity :exec
DELETE FROM entities WHERE id = ?
`

func (q *Queries) DeleteEntity(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntity, id)
	return err
}

const deleteEntityType = `-- name: DeleteEntityType :exec
DELETE FROM entity_types WHERE id = ?
`

func (q *Queries) DeleteEntityType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteEntityType, id)
	return err
}

const deleteMediaAsset = `-- name: DeleteMediaAsset :exec
DELETE FROM media_assets WHERE id = ?
`

func (q *Queries) DeleteMediaAsset(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteMediaAsset, id)
	return err
}

const deletePromptType = `-- name: DeletePromptType :exec
DELETE FROM prompt_types WHERE id = ?
`

func (q *Queries) DeletePromptType(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deletePromptType, id)
	return err
}

const deleteStory = `-- name: DeleteStory :exec
DELETE FROM stories WHERE id = ?
`

func (q *Queries) DeleteStory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStory, id)
	return err
}

const deleteStoryItem = `-- name: DeleteStoryItem :exec
DELETE FROM story_items WHERE id = ?
`

func (q *Queries) DeleteStoryItem(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteStoryItem, id)
	return err
}

const getEntityByID = `-- name: GetEntityByID :one
SELECT e.id, e.slug, e.name, e.type, e.description, e.avatar_url, e.created_at, e.base_prompt, e.entity_type_id, e.avatar_thumbnail_url, et.name as type_name, et.slug as type_slug
FROM entities e
LEFT JOIN entity_types et ON e.entity_type_id = et.id
WHERE e.id = ?
`

type GetEntityByIDRow struct {
	ID                 int64          `json:"id"`
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	Description        sql.NullString `json:"description"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
	TypeName           sql.NullString `json:"type_name"`
	TypeSlug           sql.NullString `json:"type_slug"`
}

func (q *Queries) GetEntityByID(ctx context.Context, id int64) (GetEntityByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityByID, id)
	var i GetEntityByIDRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.BasePrompt,
		&i.EntityTypeID,
		&i.AvatarThumbnailUrl,
		&i.TypeName,
		&i.TypeSlug,
	)
	return i, err
}

const getEntityBySlug = `-- name: GetEntityBySlug :one
SELECT e.id, e.slug, e.name, e.type, e.description, e.avatar_url, e.created_at, e.base_prompt, e.entity_type_id, e.avatar_thumbnail_url, et.name as type_name, et.slug as type_slug 
FROM entities e
LEFT JOIN entity_types et ON e.entity_type_id = et.id
WHERE e.slug = ?
`

type GetEntityBySlugRow struct {
	ID                 int64          `json:"id"`
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	Description        sql.NullString `json:"description"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
	TypeName           sql.NullString `json:"type_name"`
	TypeSlug           sql.NullString `json:"type_slug"`
}

func (q *Queries) GetEntityBySlug(ctx context.Context, slug string) (GetEntityBySlugRow, error) {
	row := q.db.QueryRowContext(ctx, getEntityBySlug, slug)
	var i GetEntityBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.BasePrompt,
		&i.EntityTypeID,
		&i.AvatarThumbnailUrl,
		&i.TypeName,
		&i.TypeSlug,
	)
	return i, err
}

const getEntityTypeByID = `-- name: GetEntityTypeByID :one
SELECT id, slug, name, description, created_at FROM entity_types WHERE id = ?
`

func (q *Queries) GetEntityTypeByID(ctx context.Context, id int64) (EntityType, error) {
	row := q.db.QueryRowContext(ctx, getEntityTypeByID, id)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getEntityTypeBySlug = `-- name: GetEntityTypeBySlug :one
SELECT id, slug, name, description, created_at FROM entity_types WHERE slug = ?
`

func (q *Queries) GetEntityTypeBySlug(ctx context.Context, slug string) (EntityType, error) {
	row := q.db.QueryRowContext(ctx, getEntityTypeBySlug, slug)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPromptVersion = `-- name: GetLatestPromptVersion :one
SELECT id, entity_id, type_id, version_number, prompt_text, technical_params_json, created_at FROM prompt_versions
WHERE entity_id = ? AND type_id = ?
ORDER BY version_number DESC
LIMIT 1
`

type GetLatestPromptVersionParams struct {
	EntityID int64 `json:"entity_id"`
	TypeID   int64 `json:"type_id"`
}

func (q *Queries) GetLatestPromptVersion(ctx context.Context, arg GetLatestPromptVersionParams) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestPromptVersion, arg.EntityID, arg.TypeID)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.TypeID,
		&i.VersionNumber,
		&i.PromptText,
		&i.TechnicalParamsJson,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestPromptVersionForMatrix = `-- name: GetLatestPromptVersionForMatrix :one
SELECT pv.id, pv.entity_id, pv.type_id, pv.version_number, pv.prompt_text, pv.technical_params_json, pv.created_at, e.name as entity_name, pt.slug as type_slug, pt.description as type_description
FROM prompt_versions pv
JOIN entities e ON pv.entity_id = e.id
JOIN prompt_types pt ON pv.type_id = pt.id
WHERE pv.entity_id = ? AND pv.type_id = ?
ORDER BY pv.version_number DESC
LIMIT 1
`

type GetLatestPromptVersionForMatrixParams struct {
	EntityID int64 `json:"entity_id"`
	TypeID   int64 `json:"type_id"`
}

type GetLatestPromptVersionForMatrixRow struct {
	ID                  int64          `json:"id"`
	EntityID            int64          `json:"entity_id"`
	TypeID              int64          `json:"type_id"`
	VersionNumber       int64          `json:"version_number"`
	PromptText          string         `json:"prompt_text"`
	TechnicalParamsJson sql.NullString `json:"technical_params_json"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	EntityName          string         `json:"entity_name"`
	TypeSlug            string         `json:"type_slug"`
	TypeDescription     sql.NullString `json:"type_description"`
}

func (q *Queries) GetLatestPromptVersionForMatrix(ctx context.Context, arg GetLatestPromptVersionForMatrixParams) (GetLatestPromptVersionForMatrixRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestPromptVersionForMatrix, arg.EntityID, arg.TypeID)
	var i GetLatestPromptVersionForMatrixRow
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.TypeID,
		&i.VersionNumber,
		&i.PromptText,
		&i.TechnicalParamsJson,
		&i.CreatedAt,
		&i.EntityName,
		&i.TypeSlug,
		&i.TypeDescription,
	)
	return i, err
}

const getMediaAsset = `-- name: GetMediaAsset :one
SELECT id, type, r2_key, youtube_id, source_prompt_version_id, created_at FROM media_assets WHERE id = ?
`

func (q *Queries) GetMediaAsset(ctx context.Context, id int64) (MediaAsset, error) {
	row := q.db.QueryRowContext(ctx, getMediaAsset, id)
	var i MediaAsset
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.R2Key,
		&i.YoutubeID,
		&i.SourcePromptVersionID,
		&i.CreatedAt,
	)
	return i, err
}

const getPromptTypeByID = `-- name: GetPromptTypeByID :one
SELECT id, slug, description, template_text FROM prompt_types WHERE id = ?
`

func (q *Queries) GetPromptTypeByID(ctx context.Context, id int64) (PromptType, error) {
	row := q.db.QueryRowContext(ctx, getPromptTypeByID, id)
	var i PromptType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Description,
		&i.TemplateText,
	)
	return i, err
}

const getPromptTypeBySlug = `-- name: GetPromptTypeBySlug :one
SELECT id, slug, description, template_text FROM prompt_types WHERE slug = ?
`

func (q *Queries) GetPromptTypeBySlug(ctx context.Context, slug string) (PromptType, error) {
	row := q.db.QueryRowContext(ctx, getPromptTypeBySlug, slug)
	var i PromptType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Description,
		&i.TemplateText,
	)
	return i, err
}

const getPromptVersionByID = `-- name: GetPromptVersionByID :one
SELECT id, entity_id, type_id, version_number, prompt_text, technical_params_json, created_at FROM prompt_versions WHERE id = ?
`

func (q *Queries) GetPromptVersionByID(ctx context.Context, id int64) (PromptVersion, error) {
	row := q.db.QueryRowContext(ctx, getPromptVersionByID, id)
	var i PromptVersion
	err := row.Scan(
		&i.ID,
		&i.EntityID,
		&i.TypeID,
		&i.VersionNumber,
		&i.PromptText,
		&i.TechnicalParamsJson,
		&i.CreatedAt,
	)
	return i, err
}

const getStoryByID = `-- name: GetStoryByID :one
SELECT id, title, slug, cover_image_url, published, created_at FROM stories WHERE id = ?
`

func (q *Queries) GetStoryByID(ctx context.Context, id int64) (Story, error) {
	row := q.db.QueryRowContext(ctx, getStoryByID, id)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.CoverImageUrl,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getStoryBySlug = `-- name: GetStoryBySlug :one
SELECT id, title, slug, cover_image_url, published, created_at FROM stories WHERE slug = ?
`

func (q *Queries) GetStoryBySlug(ctx context.Context, slug string) (Story, error) {
	row := q.db.QueryRowContext(ctx, getStoryBySlug, slug)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.CoverImageUrl,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const getStoryItems = `-- name: GetStoryItems :many
SELECT si.id, si.story_id, si.media_asset_id, si.sort_order FROM story_items si
WHERE si.story_id = ?
ORDER BY si.sort_order
`

func (q *Queries) GetStoryItems(ctx context.Context, storyID int64) ([]StoryItem, error) {
	rows, err := q.db.QueryContext(ctx, getStoryItems, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoryItem
	for rows.Next() {
		var i StoryItem
		if err := rows.Scan(
			&i.ID,
			&i.StoryID,
			&i.MediaAssetID,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoryWithItems = `-- name: GetStoryWithItems :one
SELECT
    s.id AS s_id, s.title AS s_title, s.slug AS s_slug, s.cover_image_url, s.published, s.created_at,
    si.id AS si_id, si.sort_order,
    ma.id AS ma_id, ma.type AS ma_type, ma.r2_key, ma.youtube_id, ma.source_prompt_version_id, ma.created_at AS ma_created_at
FROM stories s
LEFT JOIN story_items si ON s.id = si.story_id
LEFT JOIN media_assets ma ON si.media_asset_id = ma.id
WHERE s.id = ?
ORDER BY si.sort_order
`

type GetStoryWithItemsRow struct {
	SID                   int64          `json:"s_id"`
	STitle                string         `json:"s_title"`
	SSlug                 string         `json:"s_slug"`
	CoverImageUrl         sql.NullString `json:"cover_image_url"`
	Published             sql.NullBool   `json:"published"`
	CreatedAt             sql.NullTime   `json:"created_at"`
	SiID                  sql.NullInt64  `json:"si_id"`
	SortOrder             sql.NullInt64  `json:"sort_order"`
	MaID                  sql.NullInt64  `json:"ma_id"`
	MaType                sql.NullString `json:"ma_type"`
	R2Key                 sql.NullString `json:"r2_key"`
	YoutubeID             sql.NullString `json:"youtube_id"`
	SourcePromptVersionID sql.NullInt64  `json:"source_prompt_version_id"`
	MaCreatedAt           sql.NullTime   `json:"ma_created_at"`
}

func (q *Queries) GetStoryWithItems(ctx context.Context, id int64) (GetStoryWithItemsRow, error) {
	row := q.db.QueryRowContext(ctx, getStoryWithItems, id)
	var i GetStoryWithItemsRow
	err := row.Scan(
		&i.SID,
		&i.STitle,
		&i.SSlug,
		&i.CoverImageUrl,
		&i.Published,
		&i.CreatedAt,
		&i.SiID,
		&i.SortOrder,
		&i.MaID,
		&i.MaType,
		&i.R2Key,
		&i.YoutubeID,
		&i.SourcePromptVersionID,
		&i.MaCreatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, google_id, role, created_at FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByGoogleID = `-- name: GetUserByGoogleID :one
SELECT id, email, google_id, role, created_at FROM users WHERE google_id = ?
`

func (q *Queries) GetUserByGoogleID(ctx context.Context, googleID string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByGoogleID, googleID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}

const listAllMediaAssets = `-- name: ListAllMediaAssets :many
SELECT id, type, r2_key, youtube_id, source_prompt_version_id, created_at FROM media_assets ORDER BY created_at DESC
`

func (q *Queries) ListAllMediaAssets(ctx context.Context) ([]MediaAsset, error) {
	rows, err := q.db.QueryContext(ctx, listAllMediaAssets)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.R2Key,
			&i.YoutubeID,
			&i.SourcePromptVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPromptVersions = `-- name: ListAllPromptVersions :many
SELECT id, entity_id, type_id, version_number, prompt_text, technical_params_json, created_at FROM prompt_versions ORDER BY created_at DESC LIMIT 10
`

func (q *Queries) ListAllPromptVersions(ctx context.Context) ([]PromptVersion, error) {
	rows, err := q.db.QueryContext(ctx, listAllPromptVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptVersion
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.TypeID,
			&i.VersionNumber,
			&i.PromptText,
			&i.TechnicalParamsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllStories = `-- name: ListAllStories :many
SELECT id, title, slug, cover_image_url, published, created_at FROM stories ORDER BY created_at DESC
`

func (q *Queries) ListAllStories(ctx context.Context) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, listAllStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Story
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.CoverImageUrl,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntities = `-- name: ListEntities :many
SELECT e.id, e.slug, e.name, e.type, e.description, e.avatar_url, e.created_at, e.base_prompt, e.entity_type_id, e.avatar_thumbnail_url, et.name as type_name, et.slug as type_slug
FROM entities e
LEFT JOIN entity_types et ON e.entity_type_id = et.id
ORDER BY e.name
`

type ListEntitiesRow struct {
	ID                 int64          `json:"id"`
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	Description        sql.NullString `json:"description"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
	TypeName           sql.NullString `json:"type_name"`
	TypeSlug           sql.NullString `json:"type_slug"`
}

func (q *Queries) ListEntities(ctx context.Context) ([]ListEntitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntitiesRow
	for rows.Next() {
		var i ListEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.BasePrompt,
			&i.EntityTypeID,
			&i.AvatarThumbnailUrl,
			&i.TypeName,
			&i.TypeSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntitiesByType = `-- name: ListEntitiesByType :many
SELECT e.id, e.slug, e.name, e.type, e.description, e.avatar_url, e.created_at, e.base_prompt, e.entity_type_id, e.avatar_thumbnail_url, et.name as type_name, et.slug as type_slug
FROM entities e
JOIN entity_types et ON e.entity_type_id = et.id
WHERE lower(et.slug) = lower(?)
ORDER BY e.name
`

type ListEntitiesByTypeRow struct {
	ID                 int64          `json:"id"`
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	Description        sql.NullString `json:"description"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
	TypeName           string         `json:"type_name"`
	TypeSlug           string         `json:"type_slug"`
}

func (q *Queries) ListEntitiesByType(ctx context.Context, lower string) ([]ListEntitiesByTypeRow, error) {
	rows, err := q.db.QueryContext(ctx, listEntitiesByType, lower)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListEntitiesByTypeRow
	for rows.Next() {
		var i ListEntitiesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.BasePrompt,
			&i.EntityTypeID,
			&i.AvatarThumbnailUrl,
			&i.TypeName,
			&i.TypeSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityTypes = `-- name: ListEntityTypes :many
SELECT id, slug, name, description, created_at FROM entity_types ORDER BY name
`

func (q *Queries) ListEntityTypes(ctx context.Context) ([]EntityType, error) {
	rows, err := q.db.QueryContext(ctx, listEntityTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityType
	for rows.Next() {
		var i EntityType
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMediaByStory = `-- name: ListMediaByStory :many
SELECT ma.id, ma.type, ma.r2_key, ma.youtube_id, ma.source_prompt_version_id, ma.created_at FROM media_assets ma
JOIN story_items si ON ma.id = si.media_asset_id
WHERE si.story_id = ?
ORDER BY si.sort_order
`

func (q *Queries) ListMediaByStory(ctx context.Context, storyID int64) ([]MediaAsset, error) {
	rows, err := q.db.QueryContext(ctx, listMediaByStory, storyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.R2Key,
			&i.YoutubeID,
			&i.SourcePromptVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptHistory = `-- name: ListPromptHistory :many
SELECT pv.id, pv.entity_id, pv.type_id, pv.version_number, pv.prompt_text, pv.technical_params_json, pv.created_at, e.name as entity_name, pt.slug as type_slug, pt.description as type_description
FROM prompt_versions pv
JOIN entities e ON pv.entity_id = e.id
JOIN prompt_types pt ON pv.type_id = pt.id
ORDER BY pv.created_at DESC
`

type ListPromptHistoryRow struct {
	ID                  int64          `json:"id"`
	EntityID            int64          `json:"entity_id"`
	TypeID              int64          `json:"type_id"`
	VersionNumber       int64          `json:"version_number"`
	PromptText          string         `json:"prompt_text"`
	TechnicalParamsJson sql.NullString `json:"technical_params_json"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	EntityName          string         `json:"entity_name"`
	TypeSlug            string         `json:"type_slug"`
	TypeDescription     sql.NullString `json:"type_description"`
}

func (q *Queries) ListPromptHistory(ctx context.Context) ([]ListPromptHistoryRow, error) {
	rows, err := q.db.QueryContext(ctx, listPromptHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPromptHistoryRow
	for rows.Next() {
		var i ListPromptHistoryRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.TypeID,
			&i.VersionNumber,
			&i.PromptText,
			&i.TechnicalParamsJson,
			&i.CreatedAt,
			&i.EntityName,
			&i.TypeSlug,
			&i.TypeDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptTypes = `-- name: ListPromptTypes :many
SELECT id, slug, description, template_text FROM prompt_types ORDER BY slug
`

func (q *Queries) ListPromptTypes(ctx context.Context) ([]PromptType, error) {
	rows, err := q.db.QueryContext(ctx, listPromptTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptType
	for rows.Next() {
		var i PromptType
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Description,
			&i.TemplateText,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptVersionsForEntity = `-- name: ListPromptVersionsForEntity :many
SELECT id, entity_id, type_id, version_number, prompt_text, technical_params_json, created_at FROM prompt_versions WHERE entity_id = ? ORDER BY type_id, version_number DESC
`

func (q *Queries) ListPromptVersionsForEntity(ctx context.Context, entityID int64) ([]PromptVersion, error) {
	rows, err := q.db.QueryContext(ctx, listPromptVersionsForEntity, entityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptVersion
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.TypeID,
			&i.VersionNumber,
			&i.PromptText,
			&i.TechnicalParamsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptVersionsForEntityAndType = `-- name: ListPromptVersionsForEntityAndType :many
SELECT id, entity_id, type_id, version_number, prompt_text, technical_params_json, created_at FROM prompt_versions
WHERE entity_id = ? AND type_id = ?
ORDER BY version_number DESC
`

type ListPromptVersionsForEntityAndTypeParams struct {
	EntityID int64 `json:"entity_id"`
	TypeID   int64 `json:"type_id"`
}

func (q *Queries) ListPromptVersionsForEntityAndType(ctx context.Context, arg ListPromptVersionsForEntityAndTypeParams) ([]PromptVersion, error) {
	rows, err := q.db.QueryContext(ctx, listPromptVersionsForEntityAndType, arg.EntityID, arg.TypeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PromptVersion
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.TypeID,
			&i.VersionNumber,
			&i.PromptText,
			&i.TechnicalParamsJson,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublishedStories = `-- name: ListPublishedStories :many
SELECT id, title, slug, cover_image_url, published, created_at FROM stories WHERE published = 1 ORDER BY created_at DESC
`

func (q *Queries) ListPublishedStories(ctx context.Context) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, listPublishedStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Story
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.CoverImageUrl,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentEntities = `-- name: ListRecentEntities :many
SELECT e.id, e.slug, e.name, e.type, e.description, e.avatar_url, e.created_at, e.base_prompt, e.entity_type_id, e.avatar_thumbnail_url, et.name as type_name, et.slug as type_slug
FROM entities e
LEFT JOIN entity_types et ON e.entity_type_id = et.id
ORDER BY e.created_at DESC LIMIT 10
`

type ListRecentEntitiesRow struct {
	ID                 int64          `json:"id"`
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	Type               string         `json:"type"`
	Description        sql.NullString `json:"description"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	CreatedAt          sql.NullTime   `json:"created_at"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
	TypeName           sql.NullString `json:"type_name"`
	TypeSlug           sql.NullString `json:"type_slug"`
}

func (q *Queries) ListRecentEntities(ctx context.Context) ([]ListRecentEntitiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentEntities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentEntitiesRow
	for rows.Next() {
		var i ListRecentEntitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Type,
			&i.Description,
			&i.AvatarUrl,
			&i.CreatedAt,
			&i.BasePrompt,
			&i.EntityTypeID,
			&i.AvatarThumbnailUrl,
			&i.TypeName,
			&i.TypeSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentMedia = `-- name: ListRecentMedia :many
SELECT id, type, r2_key, youtube_id, source_prompt_version_id, created_at FROM media_assets ORDER BY created_at DESC LIMIT 10
`

func (q *Queries) ListRecentMedia(ctx context.Context) ([]MediaAsset, error) {
	rows, err := q.db.QueryContext(ctx, listRecentMedia)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MediaAsset
	for rows.Next() {
		var i MediaAsset
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.R2Key,
			&i.YoutubeID,
			&i.SourcePromptVersionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPromptVersions = `-- name: ListRecentPromptVersions :many
SELECT pv.id, pv.entity_id, pv.type_id, pv.version_number, pv.prompt_text, pv.technical_params_json, pv.created_at, e.name as entity_name, pt.slug as type_slug, pt.description as type_description
FROM prompt_versions pv
JOIN entities e ON pv.entity_id = e.id
JOIN prompt_types pt ON pv.type_id = pt.id
ORDER BY pv.created_at DESC LIMIT 10
`

type ListRecentPromptVersionsRow struct {
	ID                  int64          `json:"id"`
	EntityID            int64          `json:"entity_id"`
	TypeID              int64          `json:"type_id"`
	VersionNumber       int64          `json:"version_number"`
	PromptText          string         `json:"prompt_text"`
	TechnicalParamsJson sql.NullString `json:"technical_params_json"`
	CreatedAt           sql.NullTime   `json:"created_at"`
	EntityName          string         `json:"entity_name"`
	TypeSlug            string         `json:"type_slug"`
	TypeDescription     sql.NullString `json:"type_description"`
}

func (q *Queries) ListRecentPromptVersions(ctx context.Context) ([]ListRecentPromptVersionsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPromptVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPromptVersionsRow
	for rows.Next() {
		var i ListRecentPromptVersionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityID,
			&i.TypeID,
			&i.VersionNumber,
			&i.PromptText,
			&i.TechnicalParamsJson,
			&i.CreatedAt,
			&i.EntityName,
			&i.TypeSlug,
			&i.TypeDescription,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentStories = `-- name: ListRecentStories :many
SELECT id, title, slug, cover_image_url, published, created_at FROM stories ORDER BY created_at DESC LIMIT 10
`

func (q *Queries) ListRecentStories(ctx context.Context) ([]Story, error) {
	rows, err := q.db.QueryContext(ctx, listRecentStories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Story
	for rows.Next() {
		var i Story
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Slug,
			&i.CoverImageUrl,
			&i.Published,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, google_id, role, created_at FROM users ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.GoogleID,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEntity = `-- name: UpdateEntity :one
UPDATE entities
SET slug = COALESCE(?, slug),
    name = COALESCE(?, name),
    entity_type_id = COALESCE(?, entity_type_id),
    description = COALESCE(?, description),
    base_prompt = COALESCE(?, base_prompt),
    avatar_url = COALESCE(?, avatar_url),
    avatar_thumbnail_url = COALESCE(?, avatar_thumbnail_url)
WHERE id = ?
RETURNING id, slug, name, type, description, avatar_url, created_at, base_prompt, entity_type_id, avatar_thumbnail_url
`

type UpdateEntityParams struct {
	Slug               string         `json:"slug"`
	Name               string         `json:"name"`
	EntityTypeID       sql.NullInt64  `json:"entity_type_id"`
	Description        sql.NullString `json:"description"`
	BasePrompt         sql.NullString `json:"base_prompt"`
	AvatarUrl          sql.NullString `json:"avatar_url"`
	AvatarThumbnailUrl sql.NullString `json:"avatar_thumbnail_url"`
	ID                 int64          `json:"id"`
}

func (q *Queries) UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error) {
	row := q.db.QueryRowContext(ctx, updateEntity,
		arg.Slug,
		arg.Name,
		arg.EntityTypeID,
		arg.Description,
		arg.BasePrompt,
		arg.AvatarUrl,
		arg.AvatarThumbnailUrl,
		arg.ID,
	)
	var i Entity
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Type,
		&i.Description,
		&i.AvatarUrl,
		&i.CreatedAt,
		&i.BasePrompt,
		&i.EntityTypeID,
		&i.AvatarThumbnailUrl,
	)
	return i, err
}

const updateEntityType = `-- name: UpdateEntityType :one
UPDATE entity_types
SET slug = ?, name = ?, description = ?
WHERE id = ?
RETURNING id, slug, name, description, created_at
`

type UpdateEntityTypeParams struct {
	Slug        string         `json:"slug"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	ID          int64          `json:"id"`
}

func (q *Queries) UpdateEntityType(ctx context.Context, arg UpdateEntityTypeParams) (EntityType, error) {
	row := q.db.QueryRowContext(ctx, updateEntityType,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ID,
	)
	var i EntityType
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const updatePromptType = `-- name: UpdatePromptType :exec
UPDATE prompt_types SET slug = ?, description = ?, template_text = ? WHERE id = ?
`

type UpdatePromptTypeParams struct {
	Slug         string         `json:"slug"`
	Description  sql.NullString `json:"description"`
	TemplateText string         `json:"template_text"`
	ID           int64          `json:"id"`
}

func (q *Queries) UpdatePromptType(ctx context.Context, arg UpdatePromptTypeParams) error {
	_, err := q.db.ExecContext(ctx, updatePromptType,
		arg.Slug,
		arg.Description,
		arg.TemplateText,
		arg.ID,
	)
	return err
}

const updateStory = `-- name: UpdateStory :one
UPDATE stories
SET title = ?, slug = ?, cover_image_url = ?, published = ?
WHERE id = ?
RETURNING id, title, slug, cover_image_url, published, created_at
`

type UpdateStoryParams struct {
	Title         string         `json:"title"`
	Slug          string         `json:"slug"`
	CoverImageUrl sql.NullString `json:"cover_image_url"`
	Published     sql.NullBool   `json:"published"`
	ID            int64          `json:"id"`
}

func (q *Queries) UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error) {
	row := q.db.QueryRowContext(ctx, updateStory,
		arg.Title,
		arg.Slug,
		arg.CoverImageUrl,
		arg.Published,
		arg.ID,
	)
	var i Story
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Slug,
		&i.CoverImageUrl,
		&i.Published,
		&i.CreatedAt,
	)
	return i, err
}

const updateStoryItemSortOrder = `-- name: UpdateStoryItemSortOrder :exec
UPDATE story_items SET sort_order = ? WHERE id = ?
`

type UpdateStoryItemSortOrderParams struct {
	SortOrder int64 `json:"sort_order"`
	ID        int64 `json:"id"`
}

func (q *Queries) UpdateStoryItemSortOrder(ctx context.Context, arg UpdateStoryItemSortOrderParams) error {
	_, err := q.db.ExecContext(ctx, updateStoryItemSortOrder, arg.SortOrder, arg.ID)
	return err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = ? WHERE id = ?
`

type UpdateUserRoleParams struct {
	Role sql.NullString `json:"role"`
	ID   int64          `json:"id"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, updateUserRole, arg.Role, arg.ID)
	return err
}

const upsertUser = `-- name: UpsertUser :one
INSERT INTO users (email, google_id, role)
VALUES (?, ?, ?)
ON CONFLICT(email) DO UPDATE SET
    google_id = excluded.google_id,
    role = excluded.role
RETURNING id, email, google_id, role, created_at
`

type UpsertUserParams struct {
	Email    string         `json:"email"`
	GoogleID string         `json:"google_id"`
	Role     sql.NullString `json:"role"`
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, upsertUser, arg.Email, arg.GoogleID, arg.Role)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.GoogleID,
		&i.Role,
		&i.CreatedAt,
	)
	return i, err
}
