// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"
)

type Querier interface {
	AddStoryItem(ctx context.Context, arg AddStoryItemParams) (StoryItem, error)
	CreateEntity(ctx context.Context, arg CreateEntityParams) (Entity, error)
	CreateEntityType(ctx context.Context, arg CreateEntityTypeParams) (EntityType, error)
	CreateGame(ctx context.Context, arg CreateGameParams) (Game, error)
	CreateMediaAsset(ctx context.Context, arg CreateMediaAssetParams) (MediaAsset, error)
	CreateMerch(ctx context.Context, arg CreateMerchParams) (Merch, error)
	CreatePromptType(ctx context.Context, arg CreatePromptTypeParams) (PromptType, error)
	CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) (PromptVersion, error)
	CreateStory(ctx context.Context, arg CreateStoryParams) (Story, error)
	CreateVideo(ctx context.Context, arg CreateVideoParams) (Video, error)
	DeleteEntity(ctx context.Context, id int64) error
	DeleteEntityType(ctx context.Context, id int64) error
	DeleteGame(ctx context.Context, id int64) error
	DeleteMediaAsset(ctx context.Context, id int64) error
	DeleteMerch(ctx context.Context, id int64) error
	DeletePromptType(ctx context.Context, id int64) error
	DeleteStory(ctx context.Context, id int64) error
	DeleteStoryItem(ctx context.Context, id int64) error
	DeleteVideo(ctx context.Context, id int64) error
	GetEntityByID(ctx context.Context, id int64) (GetEntityByIDRow, error)
	GetEntityBySlug(ctx context.Context, slug string) (GetEntityBySlugRow, error)
	GetEntityTypeByID(ctx context.Context, id int64) (EntityType, error)
	GetEntityTypeBySlug(ctx context.Context, slug string) (EntityType, error)
	GetGame(ctx context.Context, id int64) (Game, error)
	GetLatestPromptVersion(ctx context.Context, arg GetLatestPromptVersionParams) (PromptVersion, error)
	GetLatestPromptVersionForMatrix(ctx context.Context, arg GetLatestPromptVersionForMatrixParams) (GetLatestPromptVersionForMatrixRow, error)
	GetMediaAsset(ctx context.Context, id int64) (MediaAsset, error)
	GetMerch(ctx context.Context, id int64) (Merch, error)
	GetPromptTypeByID(ctx context.Context, id int64) (PromptType, error)
	GetPromptTypeBySlug(ctx context.Context, slug string) (PromptType, error)
	GetPromptVersionByID(ctx context.Context, id int64) (PromptVersion, error)
	GetStoryByID(ctx context.Context, id int64) (Story, error)
	GetStoryBySlug(ctx context.Context, slug string) (Story, error)
	GetStoryItems(ctx context.Context, storyID int64) ([]StoryItem, error)
	GetStoryWithItems(ctx context.Context, id int64) (GetStoryWithItemsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByGoogleID(ctx context.Context, googleID string) (User, error)
	GetVideo(ctx context.Context, id int64) (Video, error)
	IncrementMerchWant(ctx context.Context, id int64) (int64, error)
	ListAllMediaAssets(ctx context.Context) ([]MediaAsset, error)
	ListAllPromptVersions(ctx context.Context) ([]PromptVersion, error)
	ListAllStories(ctx context.Context) ([]Story, error)
	ListEntities(ctx context.Context) ([]ListEntitiesRow, error)
	ListEntitiesByType(ctx context.Context, lower string) ([]ListEntitiesByTypeRow, error)
	ListEntityTypes(ctx context.Context) ([]EntityType, error)
	ListGames(ctx context.Context) ([]Game, error)
	ListLatestPromptVersionsMatrix(ctx context.Context) ([]ListLatestPromptVersionsMatrixRow, error)
	ListMediaByStory(ctx context.Context, storyID int64) ([]MediaAsset, error)
	ListMerch(ctx context.Context) ([]Merch, error)
	ListPromptHistory(ctx context.Context) ([]ListPromptHistoryRow, error)
	ListPromptTypes(ctx context.Context) ([]PromptType, error)
	ListPromptVersionsForEntity(ctx context.Context, entityID int64) ([]PromptVersion, error)
	ListPromptVersionsForEntityAndType(ctx context.Context, arg ListPromptVersionsForEntityAndTypeParams) ([]PromptVersion, error)
	ListPublishedGames(ctx context.Context) ([]Game, error)
	ListPublishedMerch(ctx context.Context) ([]Merch, error)
	ListPublishedStories(ctx context.Context) ([]Story, error)
	ListPublishedVideos(ctx context.Context) ([]Video, error)
	ListRecentEntities(ctx context.Context) ([]ListRecentEntitiesRow, error)
	ListRecentMedia(ctx context.Context) ([]MediaAsset, error)
	ListRecentPromptVersions(ctx context.Context) ([]ListRecentPromptVersionsRow, error)
	ListRecentStories(ctx context.Context) ([]Story, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListVideos(ctx context.Context) ([]Video, error)
	UpdateEntity(ctx context.Context, arg UpdateEntityParams) (Entity, error)
	UpdateEntityType(ctx context.Context, arg UpdateEntityTypeParams) (EntityType, error)
	UpdateGame(ctx context.Context, arg UpdateGameParams) (Game, error)
	UpdateMediaAsset(ctx context.Context, arg UpdateMediaAssetParams) (MediaAsset, error)
	UpdateMerch(ctx context.Context, arg UpdateMerchParams) (Merch, error)
	UpdatePromptType(ctx context.Context, arg UpdatePromptTypeParams) error
	UpdateStory(ctx context.Context, arg UpdateStoryParams) (Story, error)
	UpdateStoryItemSortOrder(ctx context.Context, arg UpdateStoryItemSortOrderParams) error
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpdateVideo(ctx context.Context, arg UpdateVideoParams) (Video, error)
	UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
